# Generated by Django 4.1.1 on 2022-10-19 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0003_clase_ubicacion_rename_usuario_profesora_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clase',
            name='fecha',
            field=models.DateField(null=True),
        ),
    ]
