# Generated by Django 4.1.1 on 2022-10-19 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0004_clase_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='clase',
            name='nombre',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
